mikepauer/Carbonite

Carbonite/NxMap.lua
this fix the issue without lost performance.
=> fix for issue #143

Carbonite.Quests/NxQuest.lua
not sure that i have found all to eliminate this bug a i can't see this bug
anymore by me
=> fix for quest itembutton

Carbonite/NxUI.lua
last fix was not complete, here the missing part after tests for weeks
=> missing fix for Questwatch QuestItemButton

Carbonite/NxOptions.lua
Fix for issue https://github.com/Rythal/Carbonite/issues/348
=> Fix for issue #348

Carbonite/Locales/deDE/HarvestNodes.lua
=> Translation Herb German

Carbonite.Quests/NxQuest.lua, Carbonite/Carbonite.lua, Carbonite/Locales/deDE/HarvestNodes.lua, Carbonite/Locales/enUS/HarvestNodes.lua, Carbonite/Locales/esES/HarvestNodes.lua, Carbonite/Locales/esMX/HarvestNodes.lua, Carbonite/Locales/frFR/HarvestNodes.lua, Carbonite/Locales/itIT/HarvestNodes.lua, Carbonite/Locales/koKR/HarvestNodes.lua, Carbonite/Locales/ptBR/HarvestNodes.lua, Carbonite/Locales/ruRU/HarvestNodes.lua, Carbonite/Locales/zhCN/HarvestNodes.lua, Carbonite/Locales/zhTW/HarvestNodes.lua, Carbonite/NxCom.lua, Carbonite/NxOptions.lua, Carbonite/NxUI.lua
withered herb update to german
=> Translation for Herb

Carbonite.Info/NxInfo.lua, Carbonite.Quests/NxQuest.lua, Carbonite.Social/NxSocial.lua, Carbonite/Carbonite.lua, Carbonite/Locales/deDE/HarvestNodes.lua, Carbonite/Locales/enUS/HarvestNodes.lua, Carbonite/Locales/esES/HarvestNodes.lua, Carbonite/Locales/esMX/HarvestNodes.lua, Carbonite/Locales/frFR/HarvestNodes.lua, Carbonite/Locales/itIT/HarvestNodes.lua, Carbonite/Locales/koKR/HarvestNodes.lua, Carbonite/Locales/ptBR/HarvestNodes.lua, Carbonite/Locales/ruRU/HarvestNodes.lua, Carbonite/Locales/zhCN/HarvestNodes.lua, Carbonite/Locales/zhTW/HarvestNodes.lua, Carbonite/NxCom.lua, Carbonite/NxOptions.lua, Carbonite/NxUI.lua
Wish if ya post to master direct you also update dev so it is current with any changes in master
=> Same as Master

Carbonite.Quests/NxQuest.lua, Carbonite.Social/NxSocial.lua, Carbonite/Carbonite.lua, Carbonite/Libs/AceGUI-3.0/widgets/AceGUIContainer-ScrollFrame.lua, Carbonite/Libs/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua, Carbonite/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua, Carbonite/Libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown-Items.lua, Carbonite/NxCom.lua, Carbonite/NxHUD.lua, Carbonite/NxMap.lua, Carbonite/NxUI.lua
I think i got some good fixes here. Many issues are covered with this one pull request.
SetTexture(number, number, number[, number]) was replaced by SetColorTexture (number, number, number[, number]). 
This was changed in WOW API 7.0.3:
*The Texture method Texture:SetTexture(R, G, B[, A]) no longer works properly in many cases. Use the new method Texture:SetColorTexture instead.*
p.s. sorry for previous broken pull requests, this pull is fine, tested.
=> Fix for some green areas/quest blobs, fix for quest detail texture (background), may fix other issues.

Carbonite/NxUI.lua
Fix for #403, but this needs more testing by other players.
=> Fix for #403

Carbonite.Quests/Data/Quests91-100.lua
Added Quests:
40593 - "Demons Among Us"
44120 - "Illidari Allies"
40661 - "Protect the Home Front"
=> Finished adding Alliance side Pre-Expansion quests

Carbonite.Quests/NxQuest.lua
=> Fix for issue #448 and #419

Carbonite/NxOptions.lua
Not much but it is some change..   Pulls it out a little more than before until some other method could be applied.
=> Increase the camera distance slightly

Carbonite/Locales/deDE/HarvestNodes.lua, Carbonite/Locales/enUS/HarvestNodes.lua, Carbonite/Locales/esES/HarvestNodes.lua, Carbonite/Locales/esMX/HarvestNodes.lua, Carbonite/Locales/frFR/HarvestNodes.lua, Carbonite/Locales/itIT/HarvestNodes.lua, Carbonite/Locales/koKR/HarvestNodes.lua, Carbonite/Locales/ptBR/HarvestNodes.lua, Carbonite/Locales/ruRU/HarvestNodes.lua, Carbonite/Locales/zhCN/HarvestNodes.lua, Carbonite/Locales/zhTW/HarvestNodes.lua
Changes to fix Locales.  Insert missing =...
=> Fix of Locations

Carbonite/Locales/frFR/FlightMasters.lua
=> Correction (s) and translation (s)

Carbonite/Data/Guides/FlightMaster.lua
Changed Zone Number because of citychange in Commit [https://github.com/mikepauer/Carbonite/commit/500511c59986be74baad06786da2d94cf8d4be86](url)
=> LC20160910-01 Thundertotem flightmaster fix

Carbonite.Warehouse/NxWarehouse.lua
Uploaded the changes, from the local copy, that is why the number of changes is so big.  Just added order resources, did not rewrite warehouse.
=> Order resources added to warehouse

Carbonite.Quests/Locales/deDE.lua, Carbonite.Quests/Locales/enUS.lua, Carbonite.Quests/Locales/esES.lua, Carbonite.Quests/Locales/esMX.lua, Carbonite.Quests/Locales/frFR.lua, Carbonite.Quests/Locales/itIT.lua, Carbonite.Quests/Locales/koKR.lua, Carbonite.Quests/Locales/ptBR.lua, Carbonite.Quests/Locales/ruRU.lua, Carbonite.Quests/Locales/zhCN.lua, Carbonite.Quests/Locales/zhTW.lua, Carbonite.Quests/NxQuest.lua
Language Term for Time Left longer then 1 Day
=> LC20161003 WorldQuest Tooltip Language Term

Carbonite.Quests/Locales/deDE.lua, Carbonite.Quests/Locales/enUS.lua, Carbonite.Quests/Locales/esES.lua, Carbonite.Quests/Locales/esMX.lua, Carbonite.Quests/Locales/frFR.lua, Carbonite.Quests/Locales/itIT.lua, Carbonite.Quests/Locales/koKR.lua, Carbonite.Quests/Locales/ptBR.lua, Carbonite.Quests/Locales/ruRU.lua, Carbonite.Quests/Locales/zhCN.lua, Carbonite.Quests/Locales/zhTW.lua
Tooltip Language Terms not needed anymore, because of ircdirks latest changes for Worlquesttooltip
=> LC20161004-01 Remove of Terms for Tooltip

Carbonite/Locales/deDE/FlightMasters.lua, Carbonite/Locales/enUS/FlightMasters.lua, Carbonite/Locales/esES/FlightMasters.lua, Carbonite/Locales/esMX/FlightMasters.lua, Carbonite/Locales/frFR/FlightMasters.lua, Carbonite/Locales/itIT/FlightMasters.lua, Carbonite/Locales/koKR/FlightMasters.lua, Carbonite/Locales/ptBR/FlightMasters.lua, Carbonite/Locales/ruRU/FlightMasters.lua, Carbonite/Locales/zhCN/FlightMasters.lua, Carbonite/Locales/zhTW/FlightMasters.lua
Changes to locales after Thrumbar's Change to flightmasters
=> LC20161010-01 Flightmaster locales added

Carbonite.Quests/Locales/zhCN.lua
=> zhCN locale update

Carbonite.Quests/NxQuest.lua
Change to bring bottom bar in line of length with top title bar for Bonus Quest
=> Cosmetic Change

Carbonite.Quests/NxQuest.lua
=> Corrected GetQuestLogLeaderBoard string vairable

Carbonite.Quests/NxQuest.lua
set the bottom bar to match length of title bar based on world quest or bonus task wording.
=> Final tweek to quest watch window

Carbonite.Quests/NxQuest.lua
TagName in line 3510 was originally just tag.  Putting it back fixed the issue.
=> Found the problem

Carbonite.Quests/NxQuest.lua
Updating watch ranges to reflect the increased level of characters not we can go to 110...
=> Update watch range

Carbonite.Quests/NxQuest.lua
Changed 15 to num to see if that shortens log, and it did, with no other side effects. Earlier fixes were over thought, when all it needed was simple change to loop.
=> fixing log to use real count

Carbonite/NxTravel.lua
=> enable direct routing for legion flying
